main: net.Zrips.CMILib.CMILib
name: CMILib
author: Zrips
version: ${project.version}
folia-supported: true
api-version: 1.13
description: CMI library
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI]
website: https://www.spigotmc.org/resources/cmilib.87610/
commands:
  cmil:
      description: basic command
      permission: cmil.parent